######/bet
POST http://localhost:8080/cars/v1/bet
Accept: application/json
Content-Type: application/json

{
  "car_brand": "bmw",
  "amount": 200
}

######/bet
POST http://localhost:8080/cars/v1/total-info
Accept: application/json
Content-Type: application/json

{
  "car_brand": null
}